apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo

spec:
  containers:
  - name: app
    image: nginx

    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_ENV

    command:
    - sh
    - -c
    - |
      while true; do
        echo "APP_ENV=$APP_ENV"
        sleep 30
      done