apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeproxy-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeproxy-lab
  template:
    metadata:
      labels:
        app: kubeproxy-lab
    spec:
      containers:
      - name: nginx
        image: nginx